import type { Stage } from '@/types';

export const STAGES: Stage[] = [
  {
    number: 1,
    slug: 'podgotovka',
    title: 'Подготовка участка',
    description: 'Геодезия, расчистка, подготовка площадки под строительство',
    defaultPhoto: '/stages/01-podgotovka.jpg',
  },
  {
    number: 2,
    slug: 'fundament',
    title: 'Фундамент',
    description: 'Заливка фундамента, гидроизоляция, обратная засыпка',
    defaultPhoto: '/stages/02-fundament.jpg',
  },
  {
    number: 3,
    slug: 'steny',
    title: 'Стены',
    description: 'Возведение несущих стен и перегородок',
    defaultPhoto: '/stages/03-steny.jpg',
  },
  {
    number: 4,
    slug: 'perekrytiya',
    title: 'Перекрытия',
    description: 'Монтаж межэтажных перекрытий',
    defaultPhoto: '/stages/04-perekrytiya.jpg',
  },
  {
    number: 5,
    slug: 'krovlya',
    title: 'Кровля',
    description: 'Стропильная система, утепление, кровельное покрытие',
    defaultPhoto: '/stages/05-krovlya.jpg',
  },
  {
    number: 6,
    slug: 'okna-dveri',
    title: 'Окна и двери',
    description: 'Установка оконных и дверных блоков',
    defaultPhoto: '/stages/06-okna-dveri.jpg',
  },
  {
    number: 7,
    slug: 'kommunikatsii',
    title: 'Коммуникации',
    description: 'Водоснабжение, канализация, электрика, отопление',
    defaultPhoto: '/stages/07-kommunikatsii.jpg',
  },
  {
    number: 8,
    slug: 'uteplenie',
    title: 'Утепление фасада',
    description: 'Теплоизоляция наружных стен',
    defaultPhoto: '/stages/08-uteplenie.jpg',
  },
  {
    number: 9,
    slug: 'shtukaturka',
    title: 'Штукатурка',
    description: 'Черновая и чистовая штукатурка стен',
    defaultPhoto: '/stages/09-shtukaturka.jpg',
  },
  {
    number: 10,
    slug: 'styazhka',
    title: 'Стяжка полов',
    description: 'Выравнивание и подготовка основания полов',
    defaultPhoto: '/stages/10-styazhka.jpg',
  },
  {
    number: 11,
    slug: 'chistovaya',
    title: 'Чистовая отделка',
    description: 'Покраска, обои, плитка, напольные покрытия',
    defaultPhoto: '/stages/11-chistovaya.jpg',
  },
  {
    number: 12,
    slug: 'fasad',
    title: 'Фасад',
    description: 'Облицовка фасада, декоративные элементы',
    defaultPhoto: '/stages/12-fasad.jpg',
  },
  {
    number: 13,
    slug: 'blagoustrojstvo',
    title: 'Благоустройство',
    description: 'Отмостка, дорожки, забор, озеленение',
    defaultPhoto: '/stages/13-blagoustrojstvo.jpg',
  },
  {
    number: 14,
    slug: 'sdacha',
    title: 'Сдача объекта',
    description: 'Финальная проверка, документы, передача ключей',
    defaultPhoto: '/stages/14-sdacha.jpg',
  },
];
