import type { Stage } from '@/types';
import type { EmployeePosition } from '@/types';

export interface StageConfig extends Stage {
  employeePosition: EmployeePosition;
}

export const STAGES: StageConfig[] = [
  {
    number: 0,
    slug: 'mechta',
    title: 'Мечта',
    description: 'Формирование бюджета и видения будущего дома',
    defaultPhoto: '/stages/00-mechta.jpg',
    employeePosition: 'manager',
  },
  {
    number: 1,
    slug: 'uchastok',
    title: 'Участок',
    description: 'Кадастр, ГПЗУ, посадка дома',
    defaultPhoto: '/stages/01-uchastok.jpg',
    employeePosition: 'manager',
  },
  {
    number: 2,
    slug: 'kompaniya',
    title: 'Компания',
    description: 'Проверка надёжности, видео-обзоры',
    defaultPhoto: '/stages/02-kompaniya.jpg',
    employeePosition: 'manager',
  },
  {
    number: 3,
    slug: 'proektirovanie',
    title: 'Проектирование',
    description: 'Выбор проекта + разработка документации',
    defaultPhoto: '/stages/03-proektirovanie.jpg',
    employeePosition: 'architect',
  },
  {
    number: 4,
    slug: 'smeta',
    title: 'Смета',
    description: 'Раздельная по этапам с индексацией цен на материалы',
    defaultPhoto: '/stages/04-smeta.jpg',
    employeePosition: 'manager',
  },
  {
    number: 5,
    slug: 'fundament-steny',
    title: 'Фундамент и стены',
    description: 'Заливка основания + возведение стен',
    defaultPhoto: '/stages/05-fundament-steny.jpg',
    employeePosition: 'foreman',
  },
  {
    number: 6,
    slug: 'krysha',
    title: 'Крыша',
    description: 'Монтаж кровли',
    defaultPhoto: '/stages/06-krysha.jpg',
    employeePosition: 'foreman',
  },
  {
    number: 7,
    slug: 'teplyj-kontur',
    title: 'Тёплый контур завершён',
    description: 'Дом закрыт: фундамент, стены, крыша готовы',
    defaultPhoto: '/stages/07-teplyj-kontur.jpg',
    employeePosition: 'project_manager',
  },
  {
    number: 8,
    slug: 'fasad',
    title: 'Отделка фасада',
    description: 'Штукатурка, клинкер, панели',
    defaultPhoto: '/stages/08-fasad.jpg',
    employeePosition: 'foreman',
  },
  {
    number: 9,
    slug: 'dizajn-proekt',
    title: 'Дизайн-проект',
    description: 'Проект интерьера',
    defaultPhoto: '/stages/09-dizajn-proekt.jpg',
    employeePosition: 'architect',
  },
  {
    number: 10,
    slug: 'otdelka',
    title: 'Внутренняя отделка',
    description: 'Отделочные работы',
    defaultPhoto: '/stages/10-otdelka.jpg',
    employeePosition: 'foreman',
  },
  {
    number: 11,
    slug: 'kommunikacii',
    title: 'Инженерные коммуникации',
    description: 'Электрика, отопление, канализация, скважина',
    defaultPhoto: '/stages/11-kommunikacii.jpg',
    employeePosition: 'foreman',
  },
  {
    number: 12,
    slug: 'landshaft',
    title: 'Ландшафтный дизайн',
    description: 'Благоустройство участка, озеленение, дорожки',
    defaultPhoto: '/stages/12-landshaft.jpg',
    employeePosition: 'foreman',
  },
  {
    number: 13,
    slug: 'zaezd',
    title: 'Заезд',
    description: 'Передача ключей',
    defaultPhoto: '/stages/13-zaezd.jpg',
    employeePosition: 'project_manager',
  },
  {
    number: 14,
    slug: 'servis',
    title: 'Сервис',
    description: 'Гарантийное обслуживание + партнёры',
    defaultPhoto: '/stages/14-servis.jpg',
    employeePosition: 'manager',
  },
];
